/*
 * Copyright 2019-2020 ,2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 9.0.0
board: IMXRT1050-EVKB
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"
#include "pad_config.h"
#include "fsl_gpio.h"
/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D10, peripheral: ARM, signal: arm_trace_swo, pin_signal: GPIO_B0_13, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
	CLOCK_EnableClock(kCLOCK_Iomuxc);           

	IOMUXC_SetPinMux(IOMUXC_GPIO_B0_13_ARM_CM7_TRACE_SWO, 0U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_05_FLEXSPIA_DQS, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 1U); 
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 1U); 

	IOMUXC_SetPinMux(IOMUXC_SNVS_WAKEUP_GPIO5_IO00, 0U); 

	/* OUTPUT */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U); //X_STEP_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U); //Y_STEP_PIN
	/* INPUT */
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_GPIO3_IO13, 0U); //X_LIMIT_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_GPIO3_IO14, 0U); //Y_LIMIT_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_GPIO3_IO15, 0U); //Z_LIMIT_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_GPIO3_IO12, 0U); //PROBE_PIN
	/* OUTPUT */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_GPIO1_IO17, 0U); //Z_STEP_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_GPIO1_IO16, 0U); //X_DIRECTION_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); //Y_DIRECTION_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); //Z_DIRECTION_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_GPIO1_IO11, 0U); //STEPPERS_ENABLE_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0U); //SPINDLE_ENABLE_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0U); //SPINDLE_DIRECTION_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_GPIO1_IO10, 0U); //SPINDLE_PWM_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0U); //COOLANT_FLOOD_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U); //COOLANT_MIST_PIN
	/* INPUT */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); //RESET_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); //FEED_HOLD_PIN
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U); //CYCLE_START_PIN

	//	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_GPIO1_IO21, 0U); //COOLANT_MIST_PIN

	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_01_GPIO1_IO17, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_00_GPIO1_IO16, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_11_GPIO1_IO11, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_10_GPIO1_IO10, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0x10B0U); 
													
//	gpio_pin_config_t input_config = 
//	{
//		.direction = kGPIO_DigitalInput,
//		.outputLogic = 1U,
//		.interruptMode = kGPIO_NoIntmode
//	};
//	gpio_pin_config_t output_config = 
//	{
//		.direction = kGPIO_DigitalOutput,
//		.outputLogic = 1U,
//		.interruptMode = kGPIO_NoIntmode
//	};
//	
//	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_GPIO3_IO13, 0x10B0U); 
//	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_02_GPIO3_IO14, 0x10B0U); 
//	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_03_GPIO3_IO15, 0x10B0U); 
//	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_GPIO3_IO12, 0x10B0U); 
//	
//	GPIO_PinInit(GPIO3,12, &output_config);
//	GPIO_PinInit(GPIO3,13, &output_config);
//	GPIO_PinInit(GPIO3,14, &output_config);
//	GPIO_PinInit(GPIO3,15, &output_config);
//	
//	GPIO_PinWrite(GPIO3,12,1);
//	GPIO_PinWrite(GPIO3,13,1);
//	GPIO_PinWrite(GPIO3,14,1);
//	GPIO_PinWrite(GPIO3,15,1);
//	
//	GPIO_PinWrite(GPIO3,12,0);
//	GPIO_PinWrite(GPIO3,13,0);
//	GPIO_PinWrite(GPIO3,14,0);
//	GPIO_PinWrite(GPIO3,15,0);
	
	/* INPUT */
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_0_100K_OHM_PULL_DOWN| \
															HYS_1_HYSTERESIS_ENABLED) ); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_0_100K_OHM_PULL_DOWN| \
															HYS_1_HYSTERESIS_ENABLED) ); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_0_100K_OHM_PULL_DOWN| \
															HYS_1_HYSTERESIS_ENABLED) );
															
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_GPIO3_IO13, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_3_22K_OHM_PULL_UP| \
															HYS_1_HYSTERESIS_ENABLED) ); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_02_GPIO3_IO14, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_3_22K_OHM_PULL_UP| \
															HYS_1_HYSTERESIS_ENABLED) );
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_03_GPIO3_IO15, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_3_22K_OHM_PULL_UP| \
															HYS_1_HYSTERESIS_ENABLED) ); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_GPIO3_IO12, (SRE_0_SLOW_SLEW_RATE| \
															DSE_0_OUTPUT_DRIVER_DISABLED| \
															SPEED_2_MEDIUM_100MHz| \
															ODE_0_OPEN_DRAIN_DISABLED| \
															PKE_1_PULL_KEEPER_ENABLED| \
															PUE_1_PULL_SELECTED| \
															PUS_3_22K_OHM_PULL_UP| \
															HYS_1_HYSTERESIS_ENABLED) ); 
	
//	GPIO_PinInit(GPIO3,12, &input_config);
//	GPIO_PinInit(GPIO3,13, &input_config);
//	GPIO_PinInit(GPIO3,14, &input_config);
//	GPIO_PinInit(GPIO3,15, &input_config);
//	uint32_t int_val = 0;
//	while(1)
//	{
//		if(GPIO_PinRead(GPIO3,12))
//		{
//			int_val |= 1<<12;
//		}
//		else
//		{
//			int_val &= ~(1<<12);
//		}
//		if(GPIO_PinRead(GPIO3,13))
//		{
//			int_val |= 1<<13;
//		}
//		else
//		{
//			int_val &= ~(1<<13);
//		}
//		if(GPIO_PinRead(GPIO3,14))
//		{
//			int_val |= 1<<14;
//		}
//		else
//		{
//			int_val &= ~(1<<14);
//		}
//		if(GPIO_PinRead(GPIO3,15))
//		{
//			int_val |= 1<<15;
//		}
//		else
//		{
//			int_val &= ~(1<<15);
//		}
//	}
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_05_FLEXSPIA_DQS, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 0x10F1U); 
	IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_13_ARM_CM7_TRACE_SWO, 0x10B0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
